### ISSUE TITLE
Cannot find module 'jollof'

### ISSUE THREAD

**Issue by shinokada** [iyobo/jollofjs#3]
![image](https://user-images.githubusercontent.com/147320/57060769-883d0b00-6cf5-11e9-9c91-89fd767263af.png)

As you can see following the doc outputs an error.

Mac v 10.14.4
node v10.15.3

**Comment by iyobo** [comment]
Try clear out your node modules and run npm install.

**Comment by shinokada** [comment]
I get the following.

```
✝ Projects/Jollof/myApp  npm install
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/koa-better-body/koa-body-parsers@git+https:/github.com/tunnckoCore/body-parsers.git#b515504ef0bfe3e04aa3dd13502d3d90c2d60956" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shinokada/.npm/_logs/2019-05-02T12_49_01_088Z-debug.log
```

**Comment by iyobo** [comment]
I just created a blank project and it worked.
That path should not exist i.e

npm ERR! Could not install from "node_modules/koa-better-body/koa-body-parsers

If anything it should be "node_modules/koa-better-body/node_modules/
koa-body-parsers.

What version of npm are you using?
-------
Iyobo Eki

**Comment by shinokada** [comment]
I use npm 6.9.0.
I tried to create a new app but got errors.

```
config/development.js not found. Using base alone
Fri May 03 2019 07:47:56 GMT+0900 (Japan Standard Time) [Environment] development settings loaded.
Fri May 03 2019 07:47:56 GMT+0900 (Japan Standard Time) 2019-05-03T07:47:56+0900 [index.js:15] JollofJS v1.6.22
Fri May 03 2019 07:47:57 GMT+0900 (Japan Standard Time)
There was an issue creating/ensuring connection to DB: http://127.0.0.1:8529 with opts: { filename: '/tmp/jollofdb',
  autoload: true,
  url: null,
  databaseName: 'jollofmvp',
  username: 'root',
  password: '' }
2019-05-03T07:47:57+0900 [bootstrap.js:52 - ERROR] Error in LoadModels Error: Error: connect ECONNREFUSED 127.0.0.1:8529
    at getConnection (/Users/shinokada/Projects/Jollof/myApp/node_modules/jollof-data-arangodb/jollofDataArangoDB.js:54:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
...more and more
```

**Comment by iyobo** [comment]
You need to have a database running. In this case, arangodb.

**Comment by iyobo** [comment]
Please follow the instructions in the first paragraph of http://jollofjs.com/#/?id=getting-started.
